blog/urls.py
from django.urls import path


from . import views


app_name = 'blog'

urlpatterns = [
    path('comment/create/', views.create_comment, name='create_comment'),
    path('ajax/image/upload/', views.ajax_image_upload, name='ajax_image_upload'),
    path('ajax/image/<int:image_id>/width/change/', views.ajax_change_width, name='ajax_change_width'),
    path('ajax/image/<int:image_id>/delete/', views.ajax_delete_image, name='ajax_delete_image'),
]

core/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.home, name='home'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('core.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
]

from django.conf import settings

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings

from .constants import WidthChoices


class Comment(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return self.name


class ImageUpload(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name='images_created')
    image = models.ImageField(upload_to='comments/')
    width = models.IntegerField(choices=WidthChoices.CHOICES, default=WidthChoices.NAM_MUOI)

blog/forms.py
from django import forms
from django.shortcuts import reverse

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from crispy_forms.bootstrap import InlineRadios

from .models import Comment, ImageUpload
from .constants import WidthChoices


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'content', )


class ImageUploadForm(forms.ModelForm):

    class Meta:
        model = ImageUpload
        fields = ('image',)


class WidthForm(forms.ModelForm):
    width = forms.ChoiceField(widget=forms.RadioSelect, choices=WidthChoices.CHOICES)

    class Meta:
        model = ImageUpload
        fields = ('width',)

    def __init__(self, *args, **kwargs):
        super(WidthForm, self).__init__(*args, **kwargs)
        self.fields['width'].label = False
        self.helper = FormHelper()
        self.helper.form_class = 'js-width-form'
        self.helper.form_action = reverse('blog:ajax_change_width', args=[self.instance.id])
        self.helper.layout = Layout(
            InlineRadios('width'),
        )

blog/views.py
import os

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from .models import Comment, ImageUpload
from .forms import CommentForm, ImageUploadForm, WidthForm


def create_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save()
            
            form = CommentForm()

    else:
        form = CommentForm()

    context = {
        'form': form,
        'comments': Comment.objects.all(),
    }

    return render(request, 'blog/comment/create.html', context)


@login_required
@require_POST
def ajax_image_upload(request):
    data = dict()

    form = ImageUploadForm(request.POST, request.FILES)
    if form.is_valid():
        image = form.save(commit=False)
        image.user = request.user
        image.save()
        data['is_valid'] = True
        form = WidthForm(instance=image)

        data['html_image'] = render_to_string('blog/comment/image.html',
                                            {'image': image, 'form': form},
                                            request=request)
            
        name = os.path.basename(image.image.name).split('.')[0]

        data['markdown_image'] = f'![{ name }]({ image.image.url }#w-{ image.width })'
    else:
        data['is_valid'] = False

    return JsonResponse(data)


@login_required
@require_POST
def ajax_change_width(request, image_id):
    data = dict()
    image = get_object_or_404(ImageUpload, id=image_id)
    form = WidthForm(request.POST, instance=image)
    if form.is_valid():
        form.save()

    name = os.path.basename(image.image.name).split('.')[0]
    data['markdown_image'] = f'![{ name }]({ image.image.url }#w-{ image.width })'

    return JsonResponse(data)


@login_required
@require_POST
def ajax_delete_image(request, image_id):
    data = dict()
    image = get_object_or_404(ImageUpload, user=request.user, id=image_id)
    image.delete()
    data['image_placeholder'] = render_to_string('blog/comment/image_placeholder.html')

    return JsonResponse(data)

core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'core/home.html')

blog/templates/blog/comment/create.html
{% extends "_base.html" %}
{% load blog %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Comment
{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'vendor/simplemde-1.11.2/simplemde.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/highlight-9.11.0/github.min.css' %}">
<script src="{% static 'vendor/highlight-9.11.0/highlight.min.js' %}"></script>
<script>hljs.initHighlightingOnLoad();</script>
<style>
    .comments img {
        max-height: 100%;
        max-width: 100%;
    }
    img[src*='#w-50'] {
        width: 50%;
    }
    img[src*='#w-75'] {
        width: 75%;
    }
    img[src*='#w-100'] {
        width: 100%;
    }
    img {
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: center; 
    }
</style>
{% endblock css %}
{% block main %}
<div class="pt-5">

    <h1 class="display-4 text-center">Markdown Example</h1>
    <p class="lead">Bình luận</p>

    <form action="." method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success btn-lg btn-block">Bình luận</button>
    </form>
    
    <h4 class="my-4 font-weight-bold">Danh sách bình luận</h4>
    <table class="table my-4 comments">
        <thead>
            <tr>
                <th scope="col">Tên</th>
                <th scope="col">Nội dung</th>
            </tr>
        </thead>
        <tbody>
            {% for comment in comments %}
            <tr>
                <td>{{ comment.name }}</td>
                <td>{{ comment.content|markdown|safe }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="modal fade" id="modalImage" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
    <div class="modal-content">
      <img class="w-100" src="" alt="">
  </div>
</div>
</div>

{% endblock main %}
{% block javascript %}
<script src="{% static 'vendor/simplemde-1.11.2/simplemde.min.js' %}"></script>
<script src="{% static 'vendor/sweetalert2/sweetalert.min.js' %}"></script>
<script src="{% static 'vendor/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'vendor/jquery-file-upload/jquery.fileupload.js' %}"></script>
<script type="text/template" id="ImageUploadTemplate">
    <div id="uploadImage">
        <div class="my-2" id="js-display-image">
            {% include "blog/comment/image_placeholder.html" %}
        </div>
        <input class="fileUpload" type="file" name="image"
                   style="display: none;"
                   data-url="{% url 'blog:ajax_image_upload' %}"
                   data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

        <div class="invalid-feedback js-error">Ảnh không hợp lệ!</div>
    </div>
</script>
<script>
var token = "{{ csrf_token }}"

var replaceTextImage = function(cm, image, text) {
    var doc = cm.getDoc();
    var cursor = doc.getCursor();
    var line = doc.getLine(cursor.line);

    var from = {
        line: cursor.line,
        ch: line.length - image.length,
    }
    var to = {
        line: cursor.line,
        ch: line.length,
    }

    doc.replaceRange(text, from, to);
}

var Toolbar_UploadImage = {
    name: "UploadImage",
    title: "Upload Image",
    className: "fa fa-upload",
    action: function(editor) {
        var cm = editor.codemirror;
        var image = '';

        swal({
            title: "Upload Image",
            content: $.parseHTML('<div>' + $('#ImageUploadTemplate').html() + '</div>')[0],
            animation: "slide-from-top",
            timer: 0,
        });

        $('#uploadImage').on('click', '.js-upload-image', function() {


            $('.fileUpload').click();
            $('.fileUpload').fileupload({
                dataTye: 'json',
                done: function(e, data) {
                    if (data.result.is_valid) {
                        $('.js-error').hide()
                        $('#js-display-image').html(data.result.html_image)
                        image = data.result.markdown_image
                        cm.replaceSelection(data.result.markdown_image);

                    } else {
                        $('.js-error').show();
                    }
                },
            });

        });

        $('#uploadImage').on('change', 'form.js-width-form', function() {
            let form = $(this);
            $.ajax({
                url: form.attr('action'),
                dataType: 'json',
                type: 'post',
                data: form.serialize(),
                success: function(data) {
                    image = data.markdown_image
                    replaceTextImage(cm, image, data.markdown_image)
                }
            });
        });


        $('#uploadImage').on('click', '.js-delete-image', function() {
            let el = $(this);
            $.ajax({
                url: el.attr('data-url'),
                type: 'post',
                dataType: 'json',
                data: {
                    csrfmiddlewaretoken: token,
                },
                success: function(data) {
                    $('#js-display-image').html(data.image_placeholder)
                    replaceTextImage(cm, image, '');
                }
            });
            return false;
        });

    }
}

function youtube_parser(url) {
    var regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/;
    var match = url.match(regExp);
    return (match && match[7].length == 11) ? match[7] : url;
}

var Toolbar_YouTube = {
    name: "YouTube",
    title: "Link YouTube",
    className: "fa fa-youtube js-youtube",
    action: function(editor) {
        var cm = editor.codemirror;

        swal({
            title: "YouTube",
            text: "Nhập link Youtube",
            content: "input",
            animation: "slide-from-top",
            inputPlaceholder: "https://",
            buttons: true,
        }).then(function(inputValue) {
            if (inputValue === false) return false;
            if (inputValue === "") {
                swal("Hãy nhập một đường link!");
                return false;
            }
            var youtubeID = youtube_parser(inputValue);
            cm.replaceSelection('[![Yes](https://img.youtube.com/vi/' + youtubeID + '/0.jpg)](https://www.youtube.com/watch?v=' + youtubeID + ')');
            swal.close();
        });
    }
}

var Toolbar_br = {
    name: "br",
    title: "Xuống dòng",
    className: "fa fa-level-down fa-rotate-90",
    action: function(editor) {
        var cm = editor.codemirror;
        cm.replaceSelection("<br />");
    }
};

$(function() {

    $('[id="id_content"').each(function(i, el) {

        var simplemde = new SimpleMDE({
            element: el,
            spellChecker: false,
            status: true,
            toolbar: [
                "undo",
                "redo",
                "|",
                "bold",
                "italic",
                "heading",
                "|",
                "table",
                "unordered-list",
                "ordered-list",
                "|",
                "link",
                "image",
                Toolbar_UploadImage,
                Toolbar_YouTube,
                "|",
                "code",
                "horizontal-rule",
                Toolbar_br,
                "|",
                "preview",
                "side-by-side",
                "fullscreen",
                "|",
                "guide",
            ],
        });
    });

    $('table.comments img').on('click', function() {
        let image = $(this);
        $('#modalImage img').attr('src', image.attr('src'));
        $('#modalImage').modal('show');
    })

});
</script>
{% endblock javascript %}

blog/templates/blog/comment/image.html
{% load crispy_forms_tags %}
<div style="width: {{  image.width }}">
    <img src="{{ image.image.url }}" style="max-height: 100%; max-width: 100%">
</div>
{% crispy form %}
<button class="btn btn-danger btn-lg my-4 js-delete-image"
        data-url="{% url 'blog:ajax_delete_image' image.id %}">
    <i class="fas fa-trash-alt mr-2"></i>
    Xóa ảnh
</button>

blog/templates/blog/comment/image_placeholder.html
<div style="border: 1px dashed; background-color: #f9f7f7; height: 279px; display: flex; justify-content: center; align-items: center;">
    <i class="fas fa-image fa-4x"></i>
</div>
<button class="btn btn-warning btn-lg text-white my-4 js-upload-image"><i class="fas fa-cloud-upload-alt mr-2"></i>Tải ảnh lên</button>

core/templates/core/about.html
{% extends "_base.html" %}
{% load i18n %}
{% block title %}
{% trans 'About' %}
{% endblock title %}
{% block main %}
<div class="text-center pt-5">
    <h1 class="display-4">{% trans 'About Page' %}</h1>
</div>
{% endblock main %}

core/templates/core/home.html
{% extends "_base.html" %}
{% block title %}
DjangoTB
{% endblock title %}
{% block main %}<div class="text-center pt-5">
    <h1 class="display-4">Home Page</h1>
    <p class="lead text-muted">Django Example</p>
    <p>
        <a href="http://djangobat.com/" class="btn btn-success my-2">djangobat.com</a>
        <a href="{% url 'blog:create_comment' %}" class="btn btn-warning my-2">Markdown Example</a>
        <a href="https://github.com/djangobat/django-example" class="btn btn-secondary my-2"><i class="fab fa-github"></i> Code Github</a>
    </p>
</div>
{% endblock main %}

templates/_base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

    <title>{% block title %}{% endblock title %}</title>
    
    <!-- SEO -->
    <meta name="author" content="djangobat">
    <meta name="description" content="Django Example">
    
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-4.4.1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/fontawesome-free-5.1.0/css/all.css' %}">
    {% block css %}
        
    {% endblock css %}
</head>
<body>
    
    {% include "includes/header.html" %}
    <div class="container">
        {% block main %}
        {% endblock main %}
    </div>
    
    <!-- JQUERY v3.4.1 -->
    <script src="{% static 'vendor/jquery-3.3.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'vendor/popper.js-1.14.6/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-4.4.1/js/bootstrap.min.js' %}"></script>
    {% block javascript %}
        
    {% endblock javascript %}
</body>
</html>

templates/includes/header.html
{% load static %}
{% load i18n %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light mb-3 bg-white border-bottom shadow-sm">
        <a href="{% url 'home' %}" class="navbar-brand my-0 mr-md-auto font-weight-normal">
            <img style="max-height: 50px" src="{% static 'images/logo-dark.png' %}" alt="">
        </a>
    </nav>
</header>